services:
  init:
    image: zephyr-build-image:latest
    build:
      context: .
    user: "1000:1000"
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - ZEPHYRPROJECT_DIR=/workspace/zephyrproject
      - ZEPHYR_SDK_INSTALL_DIR=/workspace/zephyrproject/zephyr_sdk
    command: >
      bash -c "
        rm -rf $$ZEPHYRPROJECT_DIR

        python3 -m venv $$ZEPHYRPROJECT_DIR/.venv
        source $$ZEPHYRPROJECT_DIR/.venv/bin/activate

        pip install west
        west init $$ZEPHYRPROJECT_DIR
        cd $$ZEPHYRPROJECT_DIR
        west update
        west packages pip --install

        west sdk install --install-base $$ZEPHYR_SDK_INSTALL_DIR -t arm-zephyr-eabi
      "

  interactive:
    image: zephyr-build-image:latest
    build:
      context: .
    user: "1000:1000"
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - ZEPHYRPROJECT_DIR=/workspace/zephyrproject
      - ZEPHYR_SDK_INSTALL_DIR=/workspace/zephyrproject/zephyr_sdk
      - ZEPHYR_BASE=/workspace/zephyrproject/zephyr
    command: bash -c "source $$ZEPHYRPROJECT_DIR/.venv/bin/activate && exec bash"

  interactive_root:
    image: zephyr-build-image:latest
    build:
      context: .
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - ZEPHYRPROJECT_DIR=/workspace/zephyrproject
      - ZEPHYR_SDK_INSTALL_DIR=/workspace/zephyrproject/zephyr_sdk
      - ZEPHYR_BASE=/workspace/zephyrproject/zephyr
    command: bash -c "source $$ZEPHYRPROJECT_DIR/.venv/bin/activate && exec bash"
