x-service-zephyr-base: &zephyr-base
  image: zephyr-build-image:latest
  build:
    context: .
  user: "1000:1000"
  volumes:
    - .:/workspace
  working_dir: /workspace
  environment:
    - BOARD=frdm_mcxa156
    - PROJECT_DIR=/workspace/project
    - ZEPHYRPROJECT_DIR=/workspace/zephyrproject
    - ZEPHYR_SDK_INSTALL_DIR=/workspace/zephyrproject/zephyr_sdk
    - ZEPHYR_BASE=/workspace/zephyrproject/zephyr

x-service-zephyr-debug: &zephyr-debug
  <<: *zephyr-base
  user: root
  devices:
    - /dev/bus/usb:/dev/bus/usb
    - /dev/ttyACM0:/dev/ttyACM0
  network_mode: host

services:
  init:
    <<: *zephyr-base
    command: >
      bash -c "
        rm -rf $$ZEPHYRPROJECT_DIR

        python3 -m venv $$ZEPHYRPROJECT_DIR/.venv
        source $$ZEPHYRPROJECT_DIR/.venv/bin/activate

        pip install west
        west init $$ZEPHYRPROJECT_DIR
        cd $$ZEPHYRPROJECT_DIR
        west update
        west packages pip --install

        west sdk install --install-base $$ZEPHYR_SDK_INSTALL_DIR -t arm-zephyr-eabi
      "

  build:
    <<: *zephyr-base
    command: >
      bash -c "
          source $$ZEPHYRPROJECT_DIR/.venv/bin/activate
          west build -b $$BOARD $$PROJECT_DIR
        "

  build_debug:
    <<: *zephyr-base
    command: >
      bash -c "
          source $$ZEPHYRPROJECT_DIR/.venv/bin/activate
          west build -b $$BOARD $$PROJECT_DIR -DCMAKE_BUILD_TYPE=Debug
        "
  clean:
    <<: *zephyr-base
    command: >
      bash -c "
          source $$ZEPHYRPROJECT_DIR/.venv/bin/activate
          rm -rf build
        "

  flash:
    <<: *zephyr-debug
    command: >
      bash -c "
          source $$ZEPHYRPROJECT_DIR/.venv/bin/activate
          west flash
        "

  gdb_server:
    <<: *zephyr-debug
    command: >
      bash -c "
          source $$ZEPHYRPROJECT_DIR/.venv/bin/activate
          west debugserver
        "

  interactive:
    <<: *zephyr-base
    command: >
      bash -c "
          source $$ZEPHYRPROJECT_DIR/.venv/bin/activate
          exec bash
        "

  interactive_root:
    <<: *zephyr-debug
    command: >
      bash -c "
          source $$ZEPHYRPROJECT_DIR/.venv/bin/activate
          exec bash
        "
